# Generated by Django 5.1 on 2024-08-27 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StoreBusinessHours',
        ),
        migrations.DeleteModel(
            name='StoreStatus',
        ),
        migrations.DeleteModel(
            name='StoreTimezone',
        ),
    ]
