# Generated by Django 5.1 on 2024-08-28 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0009_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statusrecord',
            name='store',
        ),
        migrations.DeleteModel(
            name='BusinessHour',
        ),
        migrations.DeleteModel(
            name='StatusRecord',
        ),
        migrations.DeleteModel(
            name='Store',
        ),
    ]
