# Generated by Django 5.1 on 2024-08-28 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0015_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BusinessHours',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
        migrations.DeleteModel(
            name='StoreStatus',
        ),
        migrations.DeleteModel(
            name='StoreTimezone',
        ),
    ]
